package it.polimi.ingsw.TCP;

public enum CMD {
    ASK_DRAW, ASK_PUT, BOARD, FROM_SERVER_CHAT, SCORE, COMMON_GOALS,
    CONNECTED, CONNECTED_REPLY, DRAW_NOT_VALID, DRAW_VALID, END_TURN, FIRST_TO_CONNECT, FIRST_TO_CONNECT_REPLY,
    IT_IS_NOT_YOUR_TURN, IT_IS_YOUR_TURN, LOBBY_IS_FULL, PERSONAL_GOAL, PLAYER_TO_PLAY, PUT_NOT_VALID,
    PUT_VALID, REPLY_ACCEPTED, REPLY_NOT_ACCEPTED, FROM_CLIENT_CHAT, WINNER,
    LAST_ROUND, LOBBY_IS_NOT_READY, BOOKSHELF, PLAYERS, USER_DISCONNECTED, RECONNECTED_REPLY,
    SEND_RECONNECTION_DATA

}

